### ISSUE TITLE
issues dumping records from Cloudflare

### ISSUE THREAD

**Issue by mihaiturcu** [octodns/octodns-cloudflare#15]
Hi,

Having some issues trying to dump existing records in CF.

Config:
```yaml
---
manager:
  max_workers: 2
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ../config
    default_ttl: 3600
    enforce_order: True
    

  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    # The api key (required)
    # Your Cloudflare account email address (required, optional if using token)
    email: env/CLOUDFLARE_EMAIL
    token: env/CLOUDFLARE_TOKEN
```

```console
source .source
(octodnsenv) ➜  config cat .source
export CLOUDFLARE_EMAIL='myemail'
export CLOUDFLARE_TOKEN='mytoken'
```

Running dump:

```console
(octodnsenv) ➜  config octodns-dump --config-file=prod.yaml --output-dir=tmp/ mydomain.tld. cloudflare --debug
2022-02-28T00:16:22  [4371137920] INFO  Manager __init__: config_file=prod.yaml
2022-02-28T00:16:22  [4371137920] INFO  Manager __init__:   max_workers=2
2022-02-28T00:16:22  [4371137920] INFO  Manager __init__:   include_meta=False
2022-02-28T00:16:22  [4371137920] DEBUG Manager __init__:   configuring providers
2022-02-28T00:16:22  [4371137920] DEBUG YamlProvider[config] __init__: id=config, directory=../config, default_ttl=3600, enforce_order=1, populate_should_replace=0
2022-02-28T00:16:22  [4371137920] DEBUG YamlProvider[config] __init__: id=config, apply_disabled=False, update_pcent_threshold=0.30, delete_pcent_threshold=0.30
2022-02-28T00:16:22  [4371137920] DEBUG CloudflareProvider[cloudflare] __init__: id=cloudflare, email=myemail, token=***, cdn=False
2022-02-28T00:16:22  [4371137920] DEBUG CloudflareProvider[cloudflare] __init__: id=cloudflare, apply_disabled=False, update_pcent_threshold=0.30, delete_pcent_threshold=0.30
Traceback (most recent call last):
  File "/Users/blk/git/octodns/octodnsenv/bin/octodns-dump", line 8, in <module>
    sys.exit(main())
  File "/Users/blk/git/octodns/octodnsenv/lib/python3.9/site-packages/octodns/cmds/dump.py", line 33, in main
    manager = Manager(args.config_file)
  File "/Users/blk/git/octodns/octodnsenv/lib/python3.9/site-packages/octodns/manager.py", line 145, in __init__
    for name in sorted(self.config['zones'].keys(), key=lambda s: s[::-1]):
KeyError: 'zones'
```

```console
(octodnsenv) ➜  config pip list | grep octodns
octodns            0.9.15
octodns-cloudflare 0.0.1
```

Dir structure:
```
(octodnsenv) ➜  octodns tree config
config
└── prod.yaml
```

mydomain.tld redacted, along with email and token
Confirming that env shows my email and token.
Cloudflare token generate from READ all template and tried granting permissions to single account / all accounts.

```
(octodnsenv) ➜  octodns python -V
Python 3.9.8
```

Thanks

**Comment by ross** [comment]
Hi @mihaiturcu,

The error is saying there's now `zones` key in your config file. That section tells octoDNS what dns zones you want to manage and where their records are sourced (usually yaml files) and where they will be targeted (in your case Cloudflare.)

That's probably going to look something like:

```yaml
zones:
  mydomain.tld.:
    sources:
      - config
    targets:
      - cloudflare
```

You'll have an entry in that section for each zone you wish to manage. `octodns-dump` doesn't strictly use that section as defined, but it still needs some of the information there in order to do its work. `octodns-sync` will use it.
